language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-android-support

jdk:
- oraclejdk8

env:
  global:
  - secure: "YgHoig6/Y99tfN2vV62cVgg1Nnh5oZQA1eCQ+ncQp+jLlpelVHELpspFf6qMM6/ha90wdyng8UgEdr+RPt6RV2HhKFJ0eG7Q2FGBeqTt7QpEVriGNl+y3/yncYaGk42kTE2Wyjxnxi2qx5Z8wO4FR35UOkXqXfpkDMfFX99LKUABww7FFlK7lFIitt2HJqB6CM/nPlvpJ0Edbw10viHylZ1K25h5o8INLo2V2QL1gagEszqHqq5XndrYkhUbfbZ4SIhhpP96vLq3HcnXoDmRtz3taD01xLRzFcGUT7f9koFjXftUSMWchXMYLxk3pVeYxJGq9TaaiNJgISuxKzlEsdgxRohl3ZU7vBGohhMKEXVLhwhfHGFqAS1fky8/1TFnESC1L7W7kChCyzG/vFE7U/kKobfQ7JYemIG519K4OX9Y7b0tjegciChCu7mrUzJK7WAd/7f2RvyQbohUnL7uOosdZCJKFpzHVJv/zO60+U1bXvc+U+PhZPdiAIPJ4HGRY9mDUMwfOfN4q3S3dUVbPqmHcr4iaXnhfGpRh66nfogtTzNlmYhe75zA1mj9ZCW3qffz0peKVWVIiSpXXa+yrUzCB5b9XAzWGXEO2QBxbmcfLSudslSNSYUHtubzWIGo/66q8Ucr3UZpdPLucFFZCdp0PtRnDIQhuPCiZPfSavo="
  - secure: "MVjJcCIwNQv+7UGf1jU0nV4p9I7WAJfPdkf5rvX+gBLn+Hu6ti77csGDsfOnS596Z8QcVETREPfJSnyaaAyZRd52aadbVCJwC7TqF07qBgpbNbe7pDiyh5Bcw4HIQ0RqaTABHt+ZEm0Cmubccmui0BW19lTj3K/aNyOt6sHKLN0BDzQYQs3EeeUeKUD9gCLUCFvYF1inic6que5d/F7WUUpvaRXyyCelNpnbLTH7HHGBfbXu5yK6q7ADBStaN+ZuHB17EXdpDiOAWyNJnm2fvST4tHMeS3e2XJTg/j5jvbLG3zh/A51NIGFqznsUMyMBRrym78NApukv0tj5UBp6FyvT3o1uEKEmLZc+VewK5dmuR9Rxc1KGj10UvkRdFdWL6fvkd8rBNwJ1h1RcD+dguP847jQSnR446yxhTn8BEt92b+LSjBw+WH3V7dAThW5/YPWxq2hinRjrZcKelJKTwdiwVXhp/rkDsWo/lhIt1TdOCPMz4nX5Ajz1HnsVvC//M++ht06zgaytV+GVESMycUWnZ9SUtzFfvTwWSoYPBr3lpHZweZgLEaaLzWkjrV2vAziuCIhQD8az/DM708FMBoitVQP820T8i6Api4OtRjH+odsk7zy8cyNDDFtTcgefrbI2Q2F7e6QpRXR/15/MzRY7SsJE99mwbZ4TQz4ZcdU="
  - secure: "RZDoXwCWs0wd+5fAJ4MrGE773h9rg3bqL9tClmgUFH+JRDFyAdn06MMHXfgehbSFhGTvHLghcSlfRPfBFW45KiaEreP4Z6S3sV3ZdXDrQgnS8dlf17ZQyo7Yh3CJg5CZTLxy9XNiJc8W4VH8WBiMhakAqgndMkIck84KwAnK6LYapcVHWdexnHsi2bxnT2KW8gJ40ElS3k7COtIDKmqbJPOoGBIgslPm7ZQbhEIRSTAujL4YYHdg6qfz17difEkr5hgivMEwZuK/Fzo/ob1MYkyM8dL0rWrnb2GAG2zu0rAaI4ZNmV8rcU5lFChUrL2ySAueh2Ew/MOjzILs4nbGZHtmlyVuEdlt87fGmCIPpKsyyYzLxLM/9r5s3EsgI1EdmdwLjrlD+EwbhevhbADb8OsmslvevlSqaSq1gWf6kC2gO+jzxfAe0ypJk4lnY3I4SJUenbEc/4fo8KBtuwtlxPIjDD5BOTX1vBVQeajlUosfJ851tAo1czrPQAAixQNYhwSqt6dCwKPHS2TzF1n8SePrTEbcVP9iP5CUMAfi1Bv4a/z5c+nJeZ2WTr/4RABwUotwMXNnFoU7BAjJXXb44oXT4Qc1IbK2fAnf/f7KVYJ2fBYKsb2OQr4+5GSDZ3o6AeKmWlLhBHRKgc+WZgF0/j/X2ZiQ/niN+/0G+uju9NI="

before_script:
  - ./pre_install.sh

script:
- cd 3d-venues-and-indoor-routing
- ./gradlew --no-daemon build
